### ISSUE TITLE
HDBSCAN soft clustering AttributeError

### ISSUE THREAD

**Issue by avissens** [scikit-learn-contrib/hdbscan#277]
I'm using HDBSCAN's soft clustering option following their tutorial. But I get this error when I try to generate `soft_clusters`:

`AttributeError: 'numpy.ndarray' object has no attribute 'condensed_tree_'`

This is my code:

    clusterer = hdbscan.HDBSCAN(
            prediction_data=True,
            min_samples=2,
            min_cluster_size=200,
            core_dist_n_jobs=1
        ).fit_predict(data)
    soft_clusters = hdbscan.all_points_membership_vectors(clusterer)

`clusterer` is a numpy array with cluster labels from:

    array([ 4, -1, 25, ..., 29, 11, 21])

Any suggestions what might be wrong? Thanks!

**Comment by lmcinnes** [comment]
The catch it that you are calling ``fit_predict`` which is returning you just the labels, and not the model -- you need the full model. Instead try something like:

```python
clusterer = hdbscan.HDBSCAN(
        prediction_data=True,
        min_samples=2,
        min_cluster_size=200,
        core_dist_n_jobs=1
    ).fit(data)
hard_clusters = clusterer.labels_
soft_clusters = hdbscan.all_points_membership_vectors(clusterer)
```

**Comment by avissens** [comment]
Oh, thanks! Now I get a different error when calling `soft_clusters`:
`ValueError: Buffer dtype mismatch, expected 'float64_t' but got 'float'`
But I suspect this is something different.

**Comment by lmcinnes** [comment]
Hmm, that's less good. Can you provide a full traceback on that? It would help me track down the issue faster. Thanks.

**Comment by avissens** [comment]
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-180-5da264f27bd6> in <module>()
      1 hard_clusters = clusterer.labels_
----> 2 soft_clusters = hdbscan.all_points_membership_vectors(clusterer)

/Applications/anaconda/envs/ipykernel_py3/lib/python3.6/site-packages/hdbscan/prediction.py in all_points_membership_vectors(clusterer)
    534         all_points,
    535         clusterer.prediction_data_.exemplars,
--> 536         clusterer.prediction_data_.dist_metric)
    537     outlier_vecs = all_points_outlier_membership_vector(
    538         clusters,

hdbscan/_prediction_utils.pyx in hdbscan._prediction_utils.all_points_dist_membership_vector()

ValueError: Buffer dtype mismatch, expected 'float64_t' but got 'float'`

**Comment by lmcinnes** [comment]
Hmm, IO thought I had weeded out most of those. I'll try to look at this soon.

**Comment by ricsinaruto** [comment]
This issue is the same as #231. I get it as well.

**Comment by lmcinnes** [comment]
Thanks for the reminder! That had some good analysis of the problem, which got me to a potential fix much faster. Hopefully this is not addressed in master. I would be happy if you could build from master and verify if this has addressed the issue.

**Comment by ricsinaruto** [comment]
I built from master, but I still get the issue in the membership_vector function. I created a simple fix: #278

**Comment by lmcinnes** [comment]
Ah, I see -- another entry to the same point of failure. Thanks for catching that.
